package ui;

import model.*;

import javax.swing.*;
import java.awt.*;

public class ViewCharacterDialog extends JDialog {
    private PlayerCharacter character;

    // MODIFY: This
    // EFFECT: Create a character information display dialog
    public ViewCharacterDialog(JFrame parent, PlayerCharacter pc) {
        super(parent, "Character Details: " + pc.getName(), true);
        this.character = pc;

        setSize(810, 630);
        setLocationRelativeTo(parent);
        setLayout(new BorderLayout(15, 10));

        add(buildTopPanel(), BorderLayout.NORTH);
        add(buildSkillPanel(), BorderLayout.CENTER);

        setVisible(true);
    }

    // EFFECT： Creat citation Lable of the Image
    private JPanel buildCitationPanel() {
        JLabel citationLabel1 = new JLabel("Fantasy-style portrait of character.");
        JLabel citationLabel2 = new JLabel("Image generated by DALL·E (OpenAI), November 7, 2025.");
        JPanel citationP = new JPanel(new GridLayout(2, 1, 10, 1));
        citationP.add(citationLabel1, BorderLayout.EAST);
        citationP.add(citationLabel2, BorderLayout.EAST);
        citationP.setBorder(BorderFactory.createEmptyBorder(5, 20, 0, 20));
        return citationP;
    }

    // EFFECT: Create top half panel of the whole window (basic info + radar chart)
    private JPanel buildTopPanel() {
        JPanel topPanel = new JPanel(new BorderLayout());
        topPanel.setPreferredSize(new Dimension(800, 390));
        topPanel.add(buildCitationPanel(), BorderLayout.SOUTH);
        topPanel.add(buildTopLeftPanel(), BorderLayout.WEST);
        topPanel.add(buildRadarJPanel(), BorderLayout.EAST);
        return topPanel;
    }

    // EFFECT: Creat top left panel
    private JPanel buildTopLeftPanel() {
        JPanel topLeftPanel = new JPanel(new BorderLayout(10, 5));
        topLeftPanel.add(buildInfoJPanel(), BorderLayout.NORTH);
        topLeftPanel.add(buildImageLabel(), BorderLayout.CENTER);
        return topLeftPanel;
    }

    // EFFECT: bulid the Jlabel for the character's pic
    private JLabel buildImageLabel() {
        String resource;
        int numImg = getNumImg(character.getName());
        String gender = character.getGender();
        if (gender.equals("other")) {
            int a = Math.floorMod(numImg, 2);
            if (a == 1) {
                resource = "src\\main\\CharacterImage\\" + "male" + "\\" + numImg + ".png";
            } else {
                resource = "src\\main\\CharacterImage\\" + "female" + "\\" + numImg + ".png";
            }
        } else {
            resource = "src\\main\\CharacterImage\\" + gender + "\\" + numImg + ".png";
        }

        ImageIcon icon = new ImageIcon(resource);

        JLabel picJLabel = new JLabel(icon);
        picJLabel.setPreferredSize(new Dimension(60, 200));
        return picJLabel;
    }

    // EFFECT: get which pic the character will use
    private int getNumImg(String s) {
        int result = 0;
        for (int i = 0; i < s.length(); i++) {
            result += (int) s.charAt(i);
        }

        return Math.floorMod(Math.abs(result), 7) + 1;
    }

    // EFFECT: Create radar chart based on chosen character
    private JPanel buildRadarJPanel() {
        JPanel radarPanel = new RadarPanel(character);
        radarPanel.setPreferredSize(new Dimension(500, 350));
        return radarPanel;
    }

    // EFFECT: Create text of basic info based on chosen character
    private JPanel buildInfoJPanel() {
        JPanel infoPanel = new JPanel(new GridLayout(3, 2, 10, 5));
        infoPanel.setBorder(BorderFactory.createEmptyBorder(10, 20, 0, 20));

        JLabel nameLabel = new JLabel("Name: " + character.getName());
        JLabel genLabel = new JLabel("Gender: " + character.getGender());

        JLabel ageLabel = new JLabel("Age: " + character.getAge());
        JLabel occLabel = new JLabel("Occupation: " + character.getOccupation());

        Font infoFont = new Font("Arial", Font.BOLD, 24);

        nameLabel.setFont(infoFont);
        genLabel.setFont(infoFont);
        ageLabel.setFont(infoFont);
        occLabel.setFont(infoFont);
        infoPanel.add(nameLabel);
        infoPanel.add(genLabel);
        infoPanel.add(ageLabel);
        infoPanel.add(occLabel);

        infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.Y_AXIS));
        infoPanel.setBorder(BorderFactory.createEmptyBorder(15, 20, 10, 10));
        infoPanel.setAlignmentY(Component.TOP_ALIGNMENT);

        return infoPanel;
    }

    // EFFECT: Create skill info string based on chosen character
    private String buildSkillInfo(PlayerCharacter pc) {
        StringBuilder sb = new StringBuilder();
        int i = 1;
        for (Skill s : pc.getSkills()) {
            sb.append(i++ + ". " + s.getName() + " : " + s.getTotalValue() + "\n");
        }
        return sb.toString();
    }

    // EFFECT: Create skill info panel based on chosen character
    private JScrollPane buildSkillPanel() {
        JTextArea skillArea = new JTextArea();
        skillArea.setEditable(false);
        skillArea.setFont(new Font("Arial", Font.PLAIN, 20));
        skillArea.setText(buildSkillInfo(character));
        JScrollPane skillPane = new JScrollPane(skillArea);
        skillPane.setBorder(BorderFactory.createTitledBorder("Skill Info:"));

        return skillPane;
    }
}
